services:
  eval-000:
    build: .
    restart: on-failure
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.eval-000.rule=HostSNI(`eval-000.cbc2025.cloud`)"
      - "traefik.tcp.routers.eval-000.tls=true"
      - "traefik.tcp.services.eval-000.loadbalancer.server.port=9101"

networks:
  traefik:
    external: true
