version: '3.8'

services:
  reduce:
    build: ./app
    volumes:
      - ./flag.txt:/flag.txt:ro
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.reduce.rule=Host(`reduce.cbc2025.cloud`)"
      - "traefik.http.routers.reduce.tls=true"
      - "traefik.http.services.reduce.loadbalancer.server.port=80"
networks:
  traefik:
    external: true