services:
  lz1:
    build: .
    restart: on-failure
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.lz1.rule=HostSNI(`lz1.cbc2025.cloud`)"
      - "traefik.tcp.routers.lz1.tls=true"
      - "traefik.tcp.services.lz1.loadbalancer.server.port=9101"

networks:
  traefik:
    external: true