version: '3'

services:
  proxy:
    image: php:8.2-apache
    restart: always
    volumes:
      - ./src:/var/www/html:ro
      - ./flag.txt:/flag.txt:ro
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nyanyanya.rule=Host(`nyanyanya.cbc2025.cloud`)"
      - "traefik.http.routers.nyanyanya.tls=true"
      - "traefik.http.services.nyanyanya.loadbalancer.server.port=80"
    
networks:
  traefik:
    external: true
