services:
  echo-000:
    build: .
    restart: on-failure
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.echo-000.rule=HostSNI(`echo-000.cbc2025.cloud`)"
      - "traefik.tcp.routers.echo-000.tls=true"
      - "traefik.tcp.services.echo-000.loadbalancer.server.port=9101"

networks:
  traefik:
    external: true
