version: '3'

services:
  poem:
    build: .
    restart: on-failure
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.constraint-label=ctf-chall"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.poem.rule=Host(`poem.cbc2025.cloud`)"
      - "traefik.http.routers.poem.entrypoints=http"
      - "traefik.http.routers.poem.middlewares=https-redirect@file"
      - "traefik.http.routers.poem-https.rule=Host(`poem.cbc2025.cloud`)"
      - "traefik.http.routers.poem-https.entrypoints=https"
      - "traefik.http.routers.poem-https.tls=true"
      - "traefik.http.routers.poem-https.tls.certresolver=le"
      - "traefik.http.services.poem-https.loadbalancer.server.port=80"    
networks:
  traefik:
    external: true
