version: '3'

services:
  proxy:
    build: .
    restart: always
    volumes:
      - ./src:/var/www/html:ro
      - ./proxy.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    # command: bash -c "a2enmod proxy proxy_http && apache2-foreground"
    networks:
      - internal
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.constraint-label=ctf-chall"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.travel-finder.rule=Host(`travel-finder.cbc2025.cloud`)"
      - "traefik.http.routers.travel-finder.entrypoints=http"
      - "traefik.http.routers.travel-finder.middlewares=https-redirect@file"
      - "traefik.http.routers.travel-finder-https.rule=Host(`travel-finder.cbc2025.cloud`)"
      - "traefik.http.routers.travel-finder-https.entrypoints=https"
      - "traefik.http.routers.travel-finder-https.tls=true"
      - "traefik.http.routers.travel-finder-https.tls.certresolver=le"
      - "traefik.http.services.travel-finder-https.loadbalancer.server.port=80"
    depends_on:
      - bot
  bot:
    platform: linux/amd64
    build:
      context: bot
      args:
        - BROWSER=chromium
    restart: always
    environment:
      APPNAME: Admin
      APPURL: http://proxy/
      APPURLREGEX: ^http(|s)://.*$
      APPFLAG: CBC{95df808c52b6753bacfa6ac9566fcd24}
      APPLIMIT: 10
      APPLIMITTIME: 60
      USE_PROXY: 1
      DISPLAY: ${DISPLAY}
    networks:
      - internal
    # uncoment this if you need to run the bot in GUI mode
    # run this before running the docker container if you're use xauth `sudo xhost +local:docker`
    # volumes:
      # - /tmp/.X11-unix:/tmp/.X11-unix

networks:
  internal:
  traefik:
    external: true
