version: '3.8'

services:
  translators:
    build: ./app
    volumes:
      - ./flag.txt:/flag.txt:ro
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.translator.rule=Host(`translator.cbc2025.cloud`)"
      - "traefik.http.routers.translator.tls=true"
      - "traefik.http.services.translator.loadbalancer.server.port=80"
networks:
  traefik:
    external: true