version: '3'

services:
  proxy:
    image: php:8.2-apache
    restart: always
    volumes:
      - ./html:/var/www/html:ro
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.constraint-label=ctf-chall"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.javascript-001.rule=Host(`javascript-001.cbc2025.cloud`)"
      - "traefik.http.routers.javascript-001.entrypoints=http"
      - "traefik.http.routers.javascript-001.middlewares=https-redirect@file"
      - "traefik.http.routers.javascript-001-https.rule=Host(`javascript-001.cbc2025.cloud`)"
      - "traefik.http.routers.javascript-001-https.entrypoints=https"
      - "traefik.http.routers.javascript-001-https.tls=true"
      - "traefik.http.routers.javascript-001-https.tls.certresolver=le"
      - "traefik.http.services.javascript-001-https.loadbalancer.server.port=80"
    
networks:
  traefik:
    external: true
