services:
  pyjail:
    build: .
    restart: on-failure
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.pyjail.rule=HostSNI(`pyjail.cbc2025.cloud`)"
      - "traefik.tcp.routers.pyjail.tls=true"
      - "traefik.tcp.services.pyjail.loadbalancer.server.port=9101"


networks:
  traefik:
    external: true
