services:
  notepad-000:
    build: .
    restart: on-failure
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.notepad-000.rule=HostSNI(`notepad-000.cbc2025.cloud`)"
      - "traefik.tcp.routers.notepad-000.tls=true"
      - "traefik.tcp.services.notepad-000.loadbalancer.server.port=9101"

networks:
  traefik:
    external: true
