version: '3.8'

services:
  mr-robot:
    build: .
    #ports:
    #  - "8080:80"
    volumes:
      - ./html:/var/www/html:ro
      - ./flag.txt:/flag.txt:ro
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.constraint-label=ctf-chall"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.mr-robot.rule=Host(`mr-robot.cbc2025.cloud`)"
      - "traefik.http.routers.mr-robot.entrypoints=http"
      - "traefik.http.routers.mr-robot.middlewares=https-redirect@file"
      - "traefik.http.routers.mr-robot-https.rule=Host(`mr-robot.cbc2025.cloud`)"
      - "traefik.http.routers.mr-robot-https.entrypoints=https"
      - "traefik.http.routers.mr-robot-https.tls=true"
      - "traefik.http.routers.mr-robot-https.tls.certresolver=le"
      - "traefik.http.services.mr-robot-https.loadbalancer.server.port=80"
networks:
  traefik:
    external: true
