services:
  dd:
    build: .
    restart: on-failure
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.dd.rule=HostSNI(`dd.cbc2025.cloud`)"
      - "traefik.tcp.routers.dd.tls=true"
      - "traefik.tcp.services.dd.loadbalancer.server.port=9101"

networks:
  traefik:
    external: true
