services:
  notepad_plus_plus-000:
    build: .
    restart: on-failure
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.constraint-label=ctf-chall"
      - "traefik.tcp.routers.notepad_plus_plus-000.rule=HostSNI(`notepad_plus_plus-000.cbc2025.cloud`)"
      - "traefik.tcp.routers.notepad_plus_plus-000.tls=true"
      - "traefik.tcp.services.notepad_plus_plus-000.loadbalancer.server.port=9101"

networks:
  traefik:
    external: true
