version: '3'

services:
  confused:
    build: .
    restart: on-failure
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.confused.rule=Host(`confused.cbc2025.cloud`)"
      - "traefik.http.routers.confused.tls=true"
      - "traefik.http.services.confused.loadbalancer.server.port=80"
    
networks:
  traefik:
    external: true
