version: '3'

services:
  letme:
    build: .
    restart: always
    volumes:
      - ./src:/var/www/html:ro
      - ./flag.txt:/flag.txt:ro
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.letme.rule=Host(`letme.cbc2025.cloud`)"
      - "traefik.http.routers.letme.tls=true"
      - "traefik.http.services.letme.loadbalancer.server.port=80"
    
networks:
  traefik:
    external: true
