services:
  cmd-000:
    build: .
    restart: on-failure
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.cmd-000.rule=HostSNI(`cmd-000.cbc2025.cloud`)"
      - "traefik.tcp.routers.cmd-000.tls=true"
      - "traefik.tcp.services.cmd-000.loadbalancer.server.port=9101"

networks:
  traefik:
    external: true
